# Generated by Django 5.0.9 on 2026-06-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_blog_event_description_blog_image_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mentor_name', models.CharField(max_length=255)),
                ('mentor_bio', models.TextField(blank=True, default='')),
                ('time', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('category', models.CharField(default='Tech', max_length=100)),
                ('duration', models.CharField(default='1 hour', max_length=100)),
                ('prerequisites', models.TextField(blank=True, default='')),
                ('syllabus', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='shop.session'),
        ),
    ]
