# Generated by Django 5.0.9 on 2026-06-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Program Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='shop_catego_name_289c7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_id_f21274_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_a2070e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_created_ef211c_idx',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='category',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mentor_bio',
        ),
        migrations.RemoveField(
            model_name='session',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='session',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='shop.programcategory'),
        ),
    ]
