# Generated by Django 5.0.9 on 2026-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_options_alter_booking_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_description',
            field=models.TextField(blank=True),
        ),
    ]
