# Generated by Django 5.0.9 on 2026-06-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_booking_notes_booking_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sessions/%Y/%m/%d'),
        ),
    ]
