# Generated by Django 5.0.9 on 2026-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_session_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='meeting_type',
            field=models.CharField(choices=[('Live', 'Live Meeting'), ('Virtual', 'Virtual (Skype)')], default='Virtual', max_length=20),
        ),
    ]
