# Generated by Django 5.0.9 on 2026-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_session_meeting_link_session_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_format',
            field=models.CharField(choices=[('Live', 'Live Meeting'), ('Virtual', 'Virtual (Skype)')], default='Virtual', max_length=20),
        ),
    ]
