# Generated by Django 5.0.9 on 2026-06-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_booking_meeting_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
