# Generated by Django 5.0.9 on 2026-06-13 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_socialmedia_followers_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'social_media')},
            },
        ),
    ]
